"""
/***************************************************************************
 BDOT10k_pluginDialog
                                 A QGIS plugin
 This plugin operates on BDOT10k.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-01-06
        git sha              : $Format:%H$
        copyright            : (C) 2022 by marylaGIS
        email                : maryla4gis@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt.QtCore import pyqtSlot
from qgis.PyQt.QtWidgets import QCheckBox, QDialog, QMessageBox

from qgis.core import QgsApplication
from qgis.utils import iface

from .utils import *
from .task_dwnl_bdot import DownloadBdotTask

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'bdot10k_dialog_base.ui'))


class BDOT10kDialogBase(QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super().__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        self.taskManager = QgsApplication.taskManager()

    @pyqtSlot()
    def on_btnClearCb_clicked(self):
        print('on_btnClearCb_clicked')
        qcbList = self.findChildren(QCheckBox)
        for qcb in qcbList:
            qcb.setChecked(False)

    def on_gbOldSchema_toggled(self):
        if self.gbOldSchema.isChecked():
            self.rbtnGML.setDisabled(True)
            self.rbtnGPKG.setDisabled(True)
        else:
            self.rbtnGML.setDisabled(False)
            self.rbtnGPKG.setDisabled(False)

    @pyqtSlot()
    def on_btnDwnl_clicked(self):
        downloadPath = self.dwnlPath.filePath()

        if self.gbOldSchema.isChecked():
            oldSchema = True
            if self.rbtnSHPold.isChecked():
                bdot10kDataFormat = 'SHP'
            elif self.rbtnGMLold.isChecked():
                bdot10kDataFormat = 'GML'
        else:
            oldSchema = False
            if self.rbtnGML.isChecked():
                bdot10kDataFormat = 'GML'
            elif self.rbtnGPKG.isChecked():
                bdot10kDataFormat = 'GPKG'

        qcbList = self.findChildren(QCheckBox)
        checkBoxList = []
        for qcb in qcbList:
            if qcb.isChecked():
                checkBoxList.append(qcb.objectName()[-4:])

        if check_dwnl_path(downloadPath) == True and len(checkBoxList) >= 1:

            task = DownloadBdotTask(
                description="Pobieranie paczek BDOT10k",
                downloadPath=downloadPath,
                oldSchema=oldSchema,
                bdot10kDataFormat=bdot10kDataFormat,
                powiatyTerytList=checkBoxList,
                iface=iface
            )

            self.taskManager.addTask(task)

        elif len(checkBoxList) == 0:
            QMessageBox.critical(self, "Błąd", "Wybierz powiat(y) do pobrania BDTO10k.")
        else:
            return False
