"""
/***************************************************************************
 BDOT10k_pluginDialog
                                 A QGIS plugin
 This plugin operates on BDOT10k.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-01-06
        git sha              : $Format:%H$
        copyright            : (C) 2022 by marylaGIS
        email                : maryla4gis@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt.QtCore import pyqtSlot
from qgis.PyQt.QtWidgets import QDialog, QMessageBox

from qgis import processing
from qgis.core import (Qgis, QgsMessageLog, QgsApplication,
                       QgsMapLayerProxyModel, QgsVectorLayer,
                       QgsCoordinateReferenceSystem)
from qgis.utils import iface

from .dialog_mixin import *
from .task_dwnl_bdot import DownloadBdotTask
from .utils import *

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'bdot10k_dialog_by_layer.ui'))


class BDOT10kDialogByLayer(QDialog, FORM_CLASS, DialogMixin):
    def __init__(self, parent=None):
        """Constructor."""
        super().__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        self.plugin_dir = os.path.dirname(__file__)
        self.powiatyTerytByLayer = []
        self.taskManager = QgsApplication.taskManager()

        # set filters for the map layer combo box - only vector layers
        self.mcbLayer.setFilters(QgsMapLayerProxyModel.PointLayer |
                                            QgsMapLayerProxyModel.LineLayer |
                                            QgsMapLayerProxyModel.PolygonLayer)
        self.txt.clear()

    def on_mcbLayer_layerChanged(self):
        layerForSelection = self.mcbLayer.currentLayer()
        layerPowiatyPath = os.path.join(self.plugin_dir, "powiaty.geojson")
        layerPowiaty = QgsVectorLayer(layerPowiatyPath, "powiaty", "ogr")

        if self.isVisible():
            if not layerForSelection:
                QMessageBox.warning(self, "Uwaga", "Wybierz warstwę wektorową.")
            elif layerForSelection and layerForSelection.featureCount() == 0:
                QMessageBox.warning(self, "Uwaga", "Wybrana warstwa nie zawiera obiektów.")
            else:                
                if layerPowiaty.crs() != QgsCoordinateReferenceSystem('EPSG:2180'):
                    layerPowiaty = processing.run("native:reprojectlayer", 
                        {'INPUT':layerPowiaty,
                        'TARGET_CRS':QgsCoordinateReferenceSystem('EPSG:2180'),
                        'OUTPUT':'TEMPORARY_OUTPUT'}
                    )['OUTPUT']

                powiatySelection = processing.run("native:selectbylocation",
                    {'INPUT': layerPowiaty,
                    'PREDICATE': [0],
                    'INTERSECT': layerForSelection,
                    'METHOD': 0}
                )

                powiatySelected = powiatySelection['OUTPUT'].selectedFeatures()

                powiatyTxt = "Powiaty: "

                if powiatySelected:
                    for feature in powiatySelected:
                        self.powiatyTerytByLayer.append(feature["teryt"])
                        powiatyTxt += feature["teryt"] + " " + feature["nazwa"] + ", "

                    powiatyCount = f"Liczba wyselekcjonowanych powiatów: {len(self.powiatyTerytByLayer)}"
                    self.txt.clear()
                    self.txt.append(powiatyCount)
                    self.txt.append(powiatyTxt)

                    return self.powiatyTerytByLayer

                else:
                    powiatyCount = f"Liczba wyselekcjonowanych powiatów: {len(self.powiatyTerytByLayer)}"
                    self.txt.clear()
                    self.txt.append(powiatyCount)
                    QMessageBox.critical(self, "Błąd", "Nie znaleziono żadnych powiatów.")

                return self.powiatyTerytByLayer

        return self.powiatyTerytByLayer

    @pyqtSlot()
    def on_btnDwnl_clicked(self):
        if not self.powiatyTerytByLayer:
            QMessageBox.critical(self, "Błąd", "Brak powiatów do pobrania.")
        else:
            downloadPath = self.dwnlPath.filePath()

            oldSchema, bdot10kDataFormat = self.get_bdot10k_data_options()

            if check_dwnl_path(downloadPath):
                QgsMessageLog.logMessage(f'Lokalizacja pobierania: {downloadPath}', 'BDOT10k', level=Qgis.MessageLevel.Info)
                QgsMessageLog.logMessage('Pobieranie paczek dla powiatów: ' + str(sorted(self.powiatyTerytByLayer)), 'BDOT10k', level=Qgis.MessageLevel.Info)

                task = DownloadBdotTask(
                    description="Pobieranie paczek BDOT10k",
                    downloadPath=downloadPath,
                    oldSchema=oldSchema,
                    bdot10kDataFormat=bdot10kDataFormat,
                    powiatyTerytList=self.powiatyTerytByLayer,
                    iface=iface
                )

                self.taskManager.addTask(task)
